# Generated by Django 5.2.3 on 2025-10-16 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.SlugField(max_length=255)),
                ('icon', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('menu_type', models.CharField(max_length=100)),
                ('target', models.CharField(choices=[('_self', 'Same tab'), ('_blank', 'New tab')], default='_self', max_length=10, verbose_name='Target')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the item is active/visible', verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, help_text='For special items (ex: "Promotion")', verbose_name='Featured')),
                ('allowed_roles', models.JSONField(blank=True, help_text='Roles that can see this menu (ex: ["admin", "user"])', null=True, verbose_name='Allowed Roles')),
                ('required_permissions', models.JSONField(blank=True, help_text='Specific permissions required', null=True, verbose_name='Required Permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('parent_menu', models.ForeignKey(blank=True, help_text='Parent menu for submenus', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='menu.menu', verbose_name='Parent Menu')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'db_table': 'menus',
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['order'], name='menus_order_136e75_idx'), models.Index(fields=['parent_menu'], name='menus_parent__4efe4e_idx'), models.Index(fields=['is_active', 'order'], name='menus_is_acti_ef7129_idx')],
            },
        ),
    ]
